export const dataSource = {};

dataSource.articles = {
  article_1: {
    id: 'article-1',
    categoryTitle: 'Prawo budowlane',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Urszula Buczak',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_2: {
    id: 'article-2',
    categoryTitle: 'Ergonomia',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Dana Werbowy',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['rybka', 'kotek', 'pies', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_3: {
    id: 'article-3',
    categoryTitle: 'Prawo budowlane',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Urszula Buczak',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_4: {
    id: 'article-4',
    categoryTitle: 'Architektura',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Urszula Buczak',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_5: {
    id: 'article-5',
    categoryTitle: 'Prawo budowlane',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Urszula Buczak',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_6: {
    id: 'article-6',
    categoryTitle: 'Wnętrza',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Urszula Buczak',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_7: {
    id: 'article-7',
    categoryTitle: 'Wnętrza',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Urszula Buczak',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_8: {
    id: 'article-5',
    categoryTitle: 'Prawo budowlane',
    title: 'Rewolucja w prawie budowlanym 2020?',
    author: 'Urszula Buczak',
    img: 'https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg',
    data: 'November 11, 2020',
    description: 'Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....',
    authorAvatar: 'https://i.postimg.cc/023ky1Hx/IMG-7794.jpg',
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },

};


dataSource.sections = {
  dział_1: {
    id: 'Dział-1',
    sectionTitle: 'Dział I',
    sectionSubTitle: 'Przepisy ogólne',
    sectionIcon: 'fab fa-simplybuilt',
  },
  dział_2: {
    id: 'Dział-2',
    sectionTitle: 'Dział II',
    sectionSubTitle: 'Zabudowa i zagospodarowanie działki budowlanej',
    sectionIcon: 'fab fa-simplybuilt',
  },
  dział_3: {
    id: 'Dział-3',
    sectionTitle: 'Dział III',
    sectionSubTitle: 'Budynki i pomieszczenia',
  },
  dział_4: {
    id: 'Dział-1',
    sectionTitle: 'Dział 1',
    sectionSubTitle: 'Przepisy ogólne',
    sectionIcon: 'fab fa-simplybuilt',
  },
  dział_5: {
    id: 'Dział-1',
    sectionTitle: 'Dział 1',
    sectionSubTitle: 'Przepisy ogólne',
    sectionIcon: 'fab fa-simplybuilt',
  },
  dział_6: {
    id: 'Dział-1',
    sectionTitle: 'Dział 1',
    sectionSubTitle: 'Przepisy ogólne',
    sectionIcon: 'fab fa-simplybuilt',
  },
};
