const dataSource = {};

dataSource.articles = {
  article_1: {
    id: "article-1",
    categoryTitle: "Prawo budowlane",
    title: "Rewolucja w prawie budowlanym 2020?",
    author: "Urszula Buczak",
    img: "https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg",
    data: "November 11, 2020",
    description: "Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....",
    authorAvatar: "https://i.postimg.cc/023ky1Hx/IMG-7794.jpg",
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_2: {
    id: "article-2",
    categoryTitle: "Design",
    title: "Rewolucja w prawie budowlanym 2020?",
    author: "Urszula Buczak",
    img: "https://i.postimg.cc/NfFJhT7t/pexels-pixabay-262367.jpg",
    data: "November 11, 2020",
    description: "Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....",
    authorAvatar: "https://i.postimg.cc/023ky1Hx/IMG-7794.jpg",
    tags: ['UX Design', 'architektura', 'ergonomia', 'środowisko', 'projekt_budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_3: {
    id: "article-1",
    categoryTitle: "Kuchnia",
    title: "Jak zaprojektować ergonomiczną kuchnię",
    author: "Urszula Buczak",
    img: "https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg",
    data: "November 11, 2020",
    description: "Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....",
    authorAvatar: "https://i.postimg.cc/023ky1Hx/IMG-7794.jpg",
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt_budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_4: {
    id: "article-1",
    categoryTitle: "Ergonomia projektowa",
    title: "Rewolucja w prawie budowlanym 2020?",
    author: "Urszula Buczak",
    img: "https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg",
    data: "November 11, 2020",
    description: "Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....",
    authorAvatar: "https://i.postimg.cc/023ky1Hx/IMG-7794.jpg",
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt_budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_5: {
    id: "article-1",
    categoryTitle: "Prawo budowlane",
    title: "Rewolucja w prawie budowlanym 2020?",
    author: "Urszula Buczak",
    img: "https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg",
    data: "November 11, 2020",
    description: "Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....",
    authorAvatar: "https://i.postimg.cc/023ky1Hx/IMG-7794.jpg",
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt_budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_6: {
    id: "article-1",
    categoryTitle: "Prawo budowlane",
    title: "Rewolucja w prawie budowlanym 2020?",
    author: "Urszula Buczak",
    img: "https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg",
    data: "November 11, 2020",
    description: "Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....",
    authorAvatar: "https://i.postimg.cc/023ky1Hx/IMG-7794.jpg",
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt_budowlany', 'kotek'],
    link: './article-1.html',
  },
  article_7: {
    id: "article-1",
    categoryTitle: "Prawo budowlane",
    title: "Lubię Żyrafa jak śpię wyśpię",
    author: "Urszula Buczak",
    img: "https://i.postimg.cc/0NdVSV4c/pexels-aleksandar-pasaric-325185.jpg",
    data: "November 11, 2020",
    description: "Duis non dolor efficitur erat interdum fringillaa lobortis dolor.Aenean in massa viverra, pretium augue et, imperdiet diam.Proin varius vitae lectus ut suscipit. Etiam....",
    authorAvatar: "https://i.postimg.cc/023ky1Hx/IMG-7794.jpg",
    tags: ['budowlanka', 'architektura', 'urząd', 'środowisko', 'projekt_budowlany', 'kotek'],
    link: './article-1.html',
  },
}
